const bridge = window.AstrBotPluginPage;
const state = { tab: 'overview', token: null, groups: [], groupId: '', settings: null, schema: null, players: [], search: '', summary: null };
const NAV = [
  ['overview','概览','▦'],['groups','群组管理','⌂'],['players','玩家中心','♙'],['economy','经济流水','￥'],['events','世界事件','✦'],
  ['settings','高级配置','⚙'],['logs','审计日志','◌'],['tutorial','新手教程','?']
];
const TITLES = {overview:['概览','世界状态、活跃度、经济与系统健康度。'],groups:['群组管理','逐群控制世界开关、Boss、事件与运行状态。'],players:['玩家中心','查看更完整的成长、活跃、财富与教程状态。'],economy:['经济流水','追踪金币、钻石的每一笔流入和流出。'],events:['世界事件','查看历史事件、天气和世界变化记录。'],settings:['高级配置','细粒度控制经济、玩法、权限、教程与群级覆盖。'],logs:['审计日志','管理员操作与玩家行为审计，便于定位异常。'],tutorial:['新手教程','查看并管理自动新手教学流程。']};
const $ = (id)=>document.getElementById(id);
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function num(v){return Number(v||0).toLocaleString('zh-CN');}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2600);}
function setTheme(ctx){document.documentElement.dataset.theme=ctx?.isDark?'dark':'light';}
async function boot(){
  const ctx=await bridge.ready(); setTheme(ctx); bridge.onContext(setTheme);
  renderNav();
  const b=await bridge.apiGet('bootstrap');
  $('versionText').textContent=`群聊世界 V${b.version||'1.4.0'} · 作者 ysgl`;
  if(!b.authenticated){ if(!b.password_configured && !(b.web_admin_usernames||[]).length){ showLogin('请先在 AstrBot 插件配置中设置“Web 管理口令”或配置 Web 超级管理员账号。'); } else showLogin(''); }
  else await loadCore();
}
function showLogin(hint){$('loginOverlay').classList.remove('hidden');$('loginHint').textContent=hint||'';}
function renderNav(){ $('nav').innerHTML=NAV.map(([id,t,i])=>`<button data-tab="${id}" class="${state.tab===id?'active':''}">${i} <span>${t}</span></button>`).join(''); $('nav').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;renderNav();render();}); }
async function login(){try{const r=await bridge.apiPost('login',{password:$('loginPassword').value});state.token=r.token;$('loginOverlay').classList.add('hidden');$('loginPassword').value='';await loadCore();toast('管理中心已解锁，有效期约 6 小时。');}catch(e){$('loginHint').textContent=e.message||'解锁失败';}}
function gparams(extra={}){return {...extra, ...(state.token?{token:state.token}:{})};}
async function apiGet(endpoint, params={}){return bridge.apiGet(endpoint,gparams(params));}
async function apiPost(endpoint, body={}){return bridge.apiPost(endpoint,{...body,...(state.token?{token:state.token}:{})});}
async function loadCore(){
  try{
    const [ov,gs,ss]=await Promise.all([apiGet('overview'),apiGet('groups'),apiGet('settings')]);
    state.summary=ov.summary||{}; state.groups=gs.groups||ov.groups||[]; state.settings=ss.config||{}; state.schema=ss.schema||{};
    if(!state.groupId) state.groupId=state.groups[0]?.group_id||'';
    renderGroupSelect(); render();
  }catch(e){ if(String(e.message).includes('无权')||String(e.message).includes('403')) showLogin(e.message); else toast(e.message||String(e)); }
}
function renderGroupSelect(){const sel=$('groupSelect');const globalOnly=['players','economy','settings','tutorial'];if(globalOnly.includes(state.tab)){sel.style.display='none';state.groupId='';return;}sel.style.display='block';sel.innerHTML=`<option value="">全部群组</option>`+state.groups.map(g=>`<option value="${esc(g.group_id)}" ${g.group_id===state.groupId?'selected':''}>${esc(g.group_id)} · ${g.player_count||0}位玩家</option>`).join('');sel.onchange=()=>{state.groupId=sel.value;render();};}
function render(){const [title,desc]=TITLES[state.tab];$('pageTitle').textContent=title;$('pageDesc').textContent=desc;renderGroupSelect();$('content').innerHTML=renderTab();attach();}
function renderTab(){switch(state.tab){case'overview':return renderOverview();case'groups':return renderGroups();case'players':return `<div id="playersRoot">加载玩家中…</div>`;case'economy':return `<div id="economyRoot">加载流水中…</div>`;case'events':return `<div id="eventsRoot">加载事件中…</div>`;case'settings':return renderSettings();case'logs':return `<div id="logsRoot">加载日志中…</div>`;case'tutorial':return renderTutorial();default:return '';}}
function renderOverview(){const summary=state.summary||{};const total=Number(summary.players||0),coins=Number(summary.coins||0),msgs=Number(summary.messages||0),boss=state.groups.filter(g=>g.boss_active).length;const active=state.groups.reduce((a,g)=>a+Number(g.today_active_users||0),0);const avg=Number(summary.avg_level||0);const max=Math.max(1,...state.groups.map(g=>Number(g.player_count||0)));
 return `<div class="grid"><div class="metric"><div class="label">群组</div><div class="value">${state.groups.length}</div><div class="sub">已被插件记录的群</div></div><div class="metric"><div class="label">玩家</div><div class="value">${num(total)}</div><div class="sub">跨群角色总数</div></div><div class="metric"><div class="label">金币流通</div><div class="value">${num(coins)}</div><div class="sub">当前玩家余额合计</div></div><div class="metric"><div class="label">世界 Boss</div><div class="value">${boss}</div><div class="sub">当前活跃 Boss 数</div></div></div>
 <div class="split"><section class="card"><div class="card-head"><div><div class="card-title">世界运行概览</div><div class="section-desc">今日活跃、消息、平均等级与各群规模。</div></div><button class="ghost small" id="overviewRefresh">刷新</button></div><div class="stat-stack"><div class="mini"><div class="k">今日活跃用户</div><div class="v">${num(active)}</div></div><div class="mini"><div class="k">累计消息</div><div class="v">${num(msgs)}</div></div><div class="mini"><div class="k">平均等级</div><div class="v">${avg.toFixed(2)}</div></div><div class="mini"><div class="k">累计探索</div><div class="v">${num(state.groups.reduce((a,g)=>a+(g.total_explores||0),0))}</div></div></div><div class="bars" style="margin-top:18px">${state.groups.slice(0,10).map(g=>`<div class="bar-row"><span>${esc(g.group_id)}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.min(100,(Number(g.player_count||0)/max)*100)}%"></div></div><b>${g.player_count||0} 人</b></div>`).join('')||'<div class="empty">暂无群数据</div>'}</div></section>
 <section class="card"><div class="card-head"><div><div class="card-title">当前群状态</div><div class="section-desc">${state.groupId?`群 ${esc(state.groupId)}`:'选择一个群查看详细状态'}</div></div></div>${renderSelectedGroup()}</section></div>`;}
function renderSelectedGroup(){const g=state.groups.find(x=>x.group_id===state.groupId)||state.groups[0];if(!g)return '<div class="empty">还没有记录到群消息。</div>';return `<div class="kv"><div>状态</div><div><span class="pill ${g.enabled?'good':'danger'}">${g.enabled?'已启用':'已关闭'}</span></div><div>天气</div><div>${esc(g.world_weather)}</div><div>地点</div><div>${esc(g.world_location)}</div><div>玩家</div><div>${num(g.player_count)}</div><div>今日消息</div><div>${num(g.today_messages)}</div><div>今日活跃</div><div>${num(g.today_active_users)}</div><div>金币流通</div><div>${num(g.coin_supply)}</div><div>钻石流通</div><div>${num(g.gem_supply)}</div><div>Boss</div><div>${g.boss_active?`${esc(g.boss_name)} · ${num(g.boss_hp)}/${num(g.boss_max_hp)}`:'暂无'}</div></div>`;}
function renderGroups(){return `<section class="card"><div class="card-head"><div><div class="card-title">群组控制台</div><div class="section-desc">后台权限高于会话管理员，群级操作全部记录审计日志。</div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>群 ID</th><th>状态</th><th>玩家</th><th>今日消息</th><th>今日活跃</th><th>金币</th><th>天气 / 地点</th><th>Boss</th><th>操作</th></tr></thead><tbody>${state.groups.map(g=>`<tr><td class="code">${esc(g.group_id)}</td><td><span class="pill ${g.enabled?'good':'danger'}">${g.enabled?'启用':'关闭'}</span></td><td>${g.player_count||0}</td><td>${num(g.today_messages)}</td><td>${num(g.today_active_users)}</td><td>${num(g.coin_supply)}</td><td>${esc(g.world_weather)} · ${esc(g.world_location)}</td><td>${g.boss_active?`${esc(g.boss_name)}<br>${num(g.boss_hp)}/${num(g.boss_max_hp)}`:'—'}</td><td><div class="actions"><button class="small" data-group-action="toggle" data-group="${esc(g.group_id)}">${g.enabled?'关闭':'开启'}</button><button class="small" data-group-action="event" data-group="${esc(g.group_id)}">触发事件</button><button class="small" data-group-action="boss_start" data-group="${esc(g.group_id)}">开 Boss</button><button class="small danger" data-group-action="boss_end" data-group="${esc(g.group_id)}">结束 Boss</button></div></td></tr>`).join('')||'<tr><td colspan="9"><div class="empty">暂无群组</div></td></tr>'}</tbody></table></div></section>`;}
function renderSettings(){const groups=[['权限与访问',['owner_user_ids','admin_user_ids','session_admin_enabled','session_admin_allowed_actions','web_admin_usernames','web_admin_password']],['群与基础',['enabled','disabled_group_ids','group_overrides_json','default_new_player_coins','default_new_player_gems','max_stamina','stamina_regen_minutes','stamina_regen_amount','new_player_protection_hours']],['经济系统',['transfer_max_coins','profession_change_cost','profession_cooldown_days','checkin_min_coins','checkin_max_coins','checkin_streak_bonus_per_day','checkin_streak_bonus_cap','shop_enabled','shop_discount_percent','shop_catalog_json']],['探索 / 成长',['explore_enabled','explore_daily_limit','explore_stamina_cost','explore_deep_extra_cost','explore_danger_extra_cost','explore_reward_multiplier','explore_rare_bonus_percent','explore_danger_percent','monster_enabled','explore_monster_chance_percent','monster_encounter_minutes','monster_reward_multiplier','monster_catalog_json','equipment_enabled','equipment_max_level','equipment_ore_cost','equipment_upgrade_base_rate','skill_system_enabled','skill_slot_limit','skill_bond_enabled']],['宠物 / 任务',['pet_enabled','pet_draw_cost','pet_draw_cooldown_seconds','pet_rarity_json','daily_tasks_enabled','daily_task_reward_multiplier','achievements_enabled']],['游戏 / 活动',['game_enabled','game_guess_reward','game_rps_win_reward','game_rps_draw_reward','game_bomb_safe_reward','fishing_enabled','fishing_stamina_cost','mining_enabled','mining_stamina_cost','work_enabled','work_cooldown_minutes']],['Boss / 世界',['boss_enabled','enable_auto_boss','boss_interval_hours','boss_duration_hours','boss_max_hp','boss_damage_base','boss_attack_cooldown_seconds','boss_top_reward','boss_reward_decay','boss_min_reward','enable_auto_world_events','world_event_interval_minutes','world_event_chance','event_catalog_json']],['教程 / 数据',['tutorial_enabled','tutorial_auto_start','tutorial_allow_skip','tutorial_pages_json','proactive_tips_enabled','proactive_tip_interval_minutes','tip_catalog_json','ai_story_enabled','data_retention_days','max_dashboard_rows']]];return `<section class="card"><div class="card-head"><div><div class="card-title">高级配置</div><div class="section-desc">优先使用本页管理复杂设置；AstrBot 原生配置页仍可作为底层配置入口。</div></div><div class="actions"><button class="ghost" id="reloadSettings">重新读取</button><button class="primary" id="saveSettings">保存全部修改</button></div></div><div class="notice"><strong>权限模型：</strong>世界超级管理员（owner_user_ids / Web 超管） ＞ 会话管理员 ＞ 玩家。默认会话管理员不允许执行高危经济、封禁和重置操作。</div>${groups.map(([title,keys])=>`<div class="form-section"><div class="card-title">${title}</div><div class="form-grid">${keys.filter(k=>state.schema[k]).map(renderField).join('')}</div></div>`).join('')}</section>`;}
function renderField(key){const sp=state.schema[key]||{}, val=state.settings[key]??sp.default??'';const desc=sp.description||key;const hint=sp.hint||'';let input='';if(sp.type==='bool'){input=`<label style="display:flex;align-items:center;gap:8px"><input data-setting="${esc(key)}" type="checkbox" ${val?'checked':''}/> <span>${esc(desc)}</span></label>`;return `<div class="field"><div>${input}</div><div class="hint">${esc(hint)}</div></div>`;}if(sp.type==='text'){input=`<textarea data-setting="${esc(key)}">${esc(val)}</textarea>`;}else if(sp.type==='int'||sp.type==='float'){input=`<input data-setting="${esc(key)}" type="number" value="${esc(val)}" ${sp.slider?`min="${sp.slider.min}" max="${sp.slider.max}" step="${sp.slider.step}"`:''}/>`;}else{input=`<input data-setting="${esc(key)}" type="${sp.secret?'password':'text'}" value="${esc(val==='********'?'':val)}" placeholder="${sp.secret?'留空表示不修改':desc}"/>`; }return `<div class="field"><label>${esc(desc)}</label>${input}<div class="hint">${esc(hint)}</div></div>`;}
function renderTutorial(){return `<section class="split"><div class="card"><div class="card-head"><div><div class="card-title">教程流程</div><div class="section-desc">玩家执行 /注册 后会自动进入第一页；每页可继续或跳过。</div></div><span class="pill good">已内置 6 页</span></div>${[1,2,3,4,5,6].map((n,i)=>`<div class="notice" style="margin-top:10px"><strong>${n}. ${['认识世界','经济与体力','探索世界','装备与宠物','小游戏与 Boss','社交与长期成长'][i]}</strong><br>${['/世界 /我的 /帮助','签到、任务、体力与经济流水','地图、普通/深度/危险探索','宠物、装备、强化','小游戏与世界 Boss','排行榜、转账、成就与长期成长'][i]}</div>`).join('')}</div><div class="card"><div class="card-head"><div class="card-title">自定义教程</div></div><div class="notice">可以在“高级配置 → 教程 / 数据”中修改 <span class="code">tutorial_pages_json</span>。示例：<div class="codebox">{"1":"欢迎加入本群！\n先输入 /签到，再输入 /探索。"}</div></div><div class="notice" style="margin-top:12px"><strong>玩家指令</strong><br><span class="code">/教程</span> 查看当前页 · <span class="code">/继续教程</span> 下一页 · <span class="code">/跳过教程</span> 结束 · <span class="code">/教程 重开</span> 重新开始</div></div></section>`;}
async function loadDynamic(){const gid=state.groupId;if(state.tab==='players'){const d=await apiGet('players',{search:state.search});state.players=d.players||[];$('playersRoot').outerHTML=renderPlayers();attach();}else if(state.tab==='economy'){const d=await apiGet('transactions',{});$('economyRoot').outerHTML=renderEconomy(d.transactions||[]);attach();}else if(state.tab==='events'){const d=await apiGet('events',{group_id:gid});$('eventsRoot').outerHTML=renderEvents(d.events||[]);attach();}else if(state.tab==='logs'){const d=await apiGet('logs',{group_id:gid});$('logsRoot').outerHTML=renderLogs(d);attach();}}
function renderPlayers(){return `<section class="card"><div class="card-head"><div><div class="card-title">玩家数据中心</div><div class="section-desc">这里只显示全局唯一玩家。同一用户跨群共享等级、金币、钻石、背包、宠物、装备与成长数据；“跨群”来自实际进入群聊世界的记录，而不是群消息数量。</div></div><div class="toolbar"><input id="playerSearch" value="${esc(state.search)}" placeholder="搜索昵称 / 用户ID"/><button class="ghost" id="searchPlayers">搜索</button></div></div><div class="notice" style="margin-bottom:12px"><strong>总玩家：${num((state.summary||{}).players||state.players.length)}</strong>　显示 ${state.players.length} 人。群聊人数不会重复计入全局玩家总数。</div><div class="table-wrap"><table class="table"><thead><tr><th>用户</th><th>跨群</th><th>成长</th><th>资产</th><th>状态</th><th>活跃</th><th>系统数据</th><th>操作</th></tr></thead><tbody>${state.players.map(p=>`<tr><td><b>${esc(p.name)}</b><br><span class="code">${esc(p.user_id)}</span></td><td>${num(p.group_count||0)} 个群<br><span class="muted">邀请 ${num(p.invite_count||0)} 人</span><br><span class="code">${esc(p.invite_code||'—')}</span></td><td>Lv.${p.level}<br>${num(p.exp)} EXP<br>${esc(p.profession)}</td><td>💰 ${num(p.coins)}<br>💎 ${num(p.gems)}<br>❤️ ${p.stamina}/${p.max_stamina}</td><td>${p.banned?'🚫 已封禁':'✅ 正常'}<br><span class="muted">${esc(p.tutorial_status||'pending')} / ${p.tutorial_step}</span></td><td>${esc(p.last_seen_at||'—')}</td><td>探索 ${num(p.total_explores)}<br>游戏 ${num(p.total_games)}<br>打工 ${num(p.total_work)}<br>Boss ${num(p.total_boss_damage)}</td><td><div class="actions"><button class="small ${p.banned?'success':'danger'}" data-player-action="${p.banned?'unban':'ban'}" data-user="${esc(p.user_id)}">${p.banned?'解封':'封禁'}</button><button class="small" data-player-action="grant_coins" data-user="${esc(p.user_id)}">+金币</button><button class="small" data-player-action="take_coins" data-user="${esc(p.user_id)}">-金币</button><button class="small" data-player-action="grant_gems" data-user="${esc(p.user_id)}">+钻石</button><button class="small" data-player-action="set_level" data-user="${esc(p.user_id)}">设等级</button><button class="small" data-player-action="edit" data-user="${esc(p.user_id)}">编辑数据</button><button class="small" data-player-action="tutorial_reset" data-user="${esc(p.user_id)}">重开教程</button><button class="small danger" data-player-action="reset" data-user="${esc(p.user_id)}">重置</button></div></td></tr>`).join('')||'<tr><td colspan="8"><div class="empty">暂无玩家</div></td></tr>'}</tbody></table></div></section>`;}
function renderEconomy(rows){return `<section class="card"><div class="card-head"><div><div class="card-title">经济流水</div><div class="section-desc">所有钱包变化都进入流水表，管理员可核查余额变化原因。</div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>时间</th><th>用户</th><th>类型</th><th>金币变化</th><th>钻石变化</th><th>变更后余额</th><th>备注</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.created_at)}</td><td class="code">${esc(r.user_id)}</td><td>${esc(r.kind)}</td><td class="${r.coins_delta>0?'good':''}">${r.coins_delta>0?'+':''}${num(r.coins_delta)}</td><td>${r.gems_delta>0?'+':''}${num(r.gems_delta)}</td><td>${num(r.coins_balance)} / 💎${num(r.gems_balance)}</td><td>${esc(r.note)}</td></tr>`).join('')||'<tr><td colspan="7"><div class="empty">暂无流水</div></td></tr>'}</tbody></table></div></section>`;}
function renderEvents(rows){return `<section class="card"><div class="card-head"><div><div class="card-title">世界事件历史</div><div class="section-desc">天气、事件类型、触发来源和描述都会保留下来。</div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>时间</th><th>类型</th><th>标题</th><th>天气</th><th>地点</th><th>触发者</th><th>详情</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.created_at)}</td><td>${esc(r.event_type)}</td><td>${esc(r.title)}</td><td>${esc(r.weather||'')}</td><td>${esc(r.location||'')}</td><td>${esc(r.triggered_by||'自动')}</td><td>${esc(r.description)}</td></tr>`).join('')||'<tr><td colspan="7"><div class="empty">暂无事件</div></td></tr>'}</tbody></table></div></section>`;}
function renderLogs(d){return `<section class="split"><div class="card"><div class="card-head"><div class="card-title">管理员审计</div></div><div class="table-wrap"><table class="table"><thead><tr><th>时间</th><th>管理员</th><th>动作</th><th>目标</th><th>详情</th></tr></thead><tbody>${(d.admin_logs||[]).map(r=>`<tr><td>${esc(r.created_at)}</td><td>${esc(r.admin_id)}</td><td>${esc(r.action)}</td><td>${esc(r.target_user_id||'')}</td><td>${esc(r.detail)}</td></tr>`).join('')||'<tr><td colspan="5"><div class="empty">暂无日志</div></td></tr>'}</tbody></table></div></div><div class="card"><div class="card-head"><div class="card-title">玩家行为</div></div><div class="table-wrap"><table class="table"><thead><tr><th>时间</th><th>用户</th><th>动作</th><th>详情</th></tr></thead><tbody>${(d.action_logs||[]).map(r=>`<tr><td>${esc(r.created_at)}</td><td>${esc(r.user_id)}</td><td>${esc(r.action)}</td><td>${esc(r.detail)}</td></tr>`).join('')||'<tr><td colspan="4"><div class="empty">暂无行为</div></td></tr>'}</tbody></table></div></div></section>`;}
async function openPlayerEditor(user){
  try{
    const p=state.players.find(x=>String(x.user_id)===String(user));
    if(!p){toast('玩家数据不存在');return;}
    $('playerModalUser').textContent=`用户ID：${user}`;
    const set=(id,v)=>$(id).value=v??'';
    set('pf_name',p.name);set('pf_level',p.level);set('pf_exp',p.exp);set('pf_coins',p.coins);set('pf_gems',p.gems);set('pf_stamina',p.stamina);set('pf_max_stamina',p.max_stamina);set('pf_hp',p.hp??p.max_stamina);set('pf_max_hp',p.max_hp??p.max_stamina);set('pf_luck',p.luck);set('pf_renown',p.renown);set('pf_profession',p.profession);set('pf_title',p.title);set('pf_streak',p.streak);set('pf_total_checkin',p.total_checkin);set('pf_tutorial_status',p.tutorial_status||'pending');set('pf_tutorial_step',p.tutorial_step||0);
    $('playerModal').classList.remove('hidden');
    $('playerSave').onclick=async()=>{
      const fields={name:$('pf_name').value.trim(),level:Number($('pf_level').value),exp:Number($('pf_exp').value),coins:Number($('pf_coins').value),gems:Number($('pf_gems').value),stamina:Number($('pf_stamina').value),max_stamina:Number($('pf_max_stamina').value),hp:Number($('pf_hp').value),max_hp:Number($('pf_max_hp').value),luck:Number($('pf_luck').value),renown:Number($('pf_renown').value),profession:$('pf_profession').value.trim(),title:$('pf_title').value.trim(),streak:Number($('pf_streak').value),total_checkin:Number($('pf_total_checkin').value),tutorial_status:$('pf_tutorial_status').value,tutorial_step:Number($('pf_tutorial_step').value)};
      try{const r=await apiPost('player/action',{user_id:user,action:'edit',fields});toast(r.message||'玩家数据已更新');$('playerModal').classList.add('hidden');await loadDynamic();}catch(e){toast(e.message||String(e));}
    };
    $('playerResetTutorial').onclick=async()=>{try{const r=await apiPost('player/action',{user_id:user,action:'tutorial_reset'});toast(r.message||'教程已重开');set('pf_tutorial_status','pending');set('pf_tutorial_step',1);await loadDynamic();}catch(e){toast(e.message||String(e));}};
  }catch(e){toast(e.message||String(e));}
}
function closePlayerEditor(){$('playerModal')?.classList.add('hidden');}
function attach(){
 $('playerModalClose')?.addEventListener('click',closePlayerEditor); $('playerModal')?.addEventListener('click',e=>{if(e.target.id==='playerModal')closePlayerEditor();});
 $('overviewRefresh')?.addEventListener('click',loadCore); $('refreshBtn').onclick=loadCore; $('exportBtn').onclick=exportData;
 $('loginBtn').onclick=login; $('loginPassword').onkeydown=e=>{if(e.key==='Enter')login();}; $('reloadSettings')?.addEventListener('click',async()=>{const d=await apiGet('settings');state.settings=d.config;state.schema=d.schema;render();toast('配置已重新读取');}); $('saveSettings')?.addEventListener('click',saveSettings);
 $('searchPlayers')?.addEventListener('click',()=>{state.search=$('playerSearch').value.trim();loadDynamic();}); $('playerSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter'){state.search=e.target.value.trim();loadDynamic();}});
 document.querySelectorAll('[data-group-action]').forEach(b=>b.onclick=async()=>{try{const r=await apiPost('group/action',{group_id:b.dataset.group,action:b.dataset.groupAction});toast(r.message||'操作成功');await loadCore();}catch(e){toast(e.message||String(e));}});
 document.querySelectorAll('[data-player-action]').forEach(b=>b.onclick=async()=>{const action=b.dataset.playerAction;const user=b.dataset.user;let amount=0;if(['grant_coins','take_coins','grant_gems'].includes(action)){amount=Number.parseInt(prompt(action==='set_level'?'设置等级：':'请输入数值：',action==='set_level'?'10':'1000')||'0',10);if(!Number.isFinite(amount))return;}if(action==='edit'||action==='set_level'){openPlayerEditor(user);return;}if(action==='reset'&&!confirm('确认重置该玩家？这是全局角色重置，会清空跨群共享的背包、宠物、装备、成就和技能。'))return;try{const r=await apiPost('player/action',{user_id:user,action,amount});toast(r.message||'玩家操作成功');await loadDynamic();}catch(e){toast(e.message||String(e));}});
 if(state.tab!=='overview'&&state.tab!=='groups'&&state.tab!=='settings'&&state.tab!=='tutorial')loadDynamic();
}
async function saveSettings(){const changes={};document.querySelectorAll('[data-setting]').forEach(el=>{const key=el.dataset.setting,sp=state.schema[key]||{};if(sp.type==='bool')changes[key]=el.checked;else if(sp.type==='int')changes[key]=Number.parseInt(el.value||'0',10);else if(sp.type==='float')changes[key]=Number.parseFloat(el.value||'0');else if(sp.type==='text')changes[key]=el.value;else if(sp.secret&&el.value===''){}else changes[key]=el.value;});try{const r=await apiPost('settings/save',{changes});state.settings=r.config||state.settings;toast('全部配置保存成功');render();}catch(e){toast(e.message||String(e));}}
async function exportData(){try{const r=await bridge.download('data/export',gparams({group_id:state.groupId||''}),'group-world-export.json');toast(`导出已生成：${r.filename||'group-world-export.json'}`);}catch(e){toast(e.message||String(e));}}
$('refreshBtn').onclick=loadCore; $('exportBtn').onclick=exportData; $('loginBtn').onclick=login; $('loginPassword').onkeydown=e=>{if(e.key==='Enter')login();};
boot().catch(e=>showLogin(e.message||String(e)));
